---
- hosts: webserver
  become: true
  become_user: root
  vars:
    src_path: /project/
    dest_path: /var/www/html
  tasks:
  - name: Install the httpd package
    yum: name=httpd state=latest
  - name: Start the httpd service
    service: name=httpd state=started
  - name: Deploy the war file
    copy: src={{src_path}}/website dest={{dest_path}}
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=started
