#update Repo
RUN apt-get update -y

#install apache
RUN apt-get install -y apache2

#install php
RUN apt-get install -y php*

#copy application files
RUN rm -rf /var/www/html/*
ADD website /var/www/html

#configure Apache
RUN chown -R www-data:www-data /var/www
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

#Port 80
EXPOSE 80

#start the service
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
